{{- include "easybpm.validateLicense" . }}
{{- if and .Values.secrets.create (not .Values.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easybpm.secretName" . }}
  labels:
    {{- include "easybpm.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.secrets.postgres.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.postgres.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  SPRING_RABBITMQ_HOST: {{ .Values.secrets.rabbitmq.host | quote }}
  SPRING_RABBITMQ_PORT: {{ .Values.secrets.rabbitmq.port | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.secrets.rabbitmq.username | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmq.password | quote }}
  EASYBPM_SECURITY_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.secrets.security.adminUsername | quote }}
  EASYBPM_SECURITY_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.security.adminPassword | quote }}
  EASYBPM_SECURITY_JWT_SECRET: {{ .Values.secrets.security.jwtSecretBase64 | quote }}
  AI_ENCRYPTION_KEY: {{ .Values.secrets.ai.encryptionKey | quote }}
  {{ include "easybpm.licenseSecretKey" . }}: {{ .Values.license.key | quote }}
{{- end }}
