apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "easybpm.fullname" . }}-worker
  labels:
    {{- include "easybpm.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "easybpm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "easybpm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "easybpm.image" (merge (dict "image" .Values.worker.image) .) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: EASY_BPM_WORKER_LOGGING_LEVEL_APP
              value: {{ .Values.config.loggingLevelComEasyBpm | quote }}
          envFrom:
            - secretRef:
                name: {{ include "easybpm.secretName" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
