CREATE TABLE "process_definition" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "version" INTEGER NOT NULL,
    "definition_json" CLOB NOT NULL
);

CREATE TABLE "process_instance" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "process_definition_id" BIGINT,
    "status" INTEGER,
    "current_nodes" CLOB,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP
);

CREATE TABLE "process_variable" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "process_instance_id" BIGINT,
    "name" VARCHAR(255) NOT NULL,
    "value" CLOB
);

CREATE TABLE "form" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "schema" CLOB NOT NULL,
    "version" INTEGER NOT NULL,
    "created_at" TIMESTAMP
);

CREATE TABLE "task" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "process_instance_id" BIGINT NOT NULL,
    "title" VARCHAR(255),
    "node_id" VARCHAR(255) NOT NULL,
    "assignee" VARCHAR(255),
    "status" VARCHAR(255),
    "created_at" TIMESTAMP,
    "completed_at" TIMESTAMP,
    "form_id" BIGINT
);

CREATE TABLE "task_variable" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "value" CLOB
);
